import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import getPages from '@/utils/getPages'
import React, { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })
interface PageData {
  path: string;
  title: string;
  description: string;
  // add any other fields you need here
}


const Home: React.FC = () => {

  const [pages, setPages] = useState();
  useEffect(() => {
    const fetchData = async () => {
      try {
        const pagesData = await getPages();
        setPages(pagesData);
      } catch (error) {
        console.error(error);
      }
    };
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1> Data </h1>
      <ul>
        {pages.map((page) => (
          <li key={page.path}>
            <a href={page.path}>{page.title}</a>
          </li>
        ))}
      </ul>
      </main>
    </>
  )
}

export default Home;
